apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: gitops-lab
    namespace: argocd

spec:
    project: default

    source:
        repoURL: https://github.com/haotzops/k8slab-005.git
        targetRevision: main
        path: clusters/orbstack

    destination:
        server: https://kubernetes.default.svc
        namespace: gitops-lab

    syncPolicy:
        automated:
            enabled: true
            prune: true
            selfHeal: true

        syncOptions:
            - CreateNamespace=true
